build_from:
  aarch64: "ghcr.io/kvanzuijlen/ankerctl:v1.0.0"
  amd64: "ghcr.io/kvanzuijlen/ankerctl:v1.0.0"
  armv7: "ghcr.io/kvanzuijlen/ankerctl:v1.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AnkerCTL"
  org.opencontainers.image.description: "AnkerCTL"
  org.opencontainers.image.source: "https://github.com/AnkerMGMT/AnkerMGMT-homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
