name: "ankerctl"
description: "The official ankerctl addon"
version: "1.0.0-0"
slug: "ankerctl"
ingress: false # Doesn't work yet, might need some source code changes
ingress_port: 4470
ingress_stream: false
init: false
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
ports:
  "4470": 4470
ports_description:
  "4470": "The webinterface for ankerctl"
